image: 
  repository: ghcr.io/project-zot/zot-linux-arm64

configFiles:
  config.json: |-
    {
      "storage": { "rootDirectory": "/var/lib/registry" },
      "http": { "address": "0.0.0.0", "port": "5000" },
      "log": { "level": "debug" },
      "extensions": { "enabled": true }
    }

service:
  type: ClusterIP

ingress:
  enabled: true
  className: nginx
  pathtype: Prefix
  hosts:
    - host: zot-registry.apps.vagrant-k8s-experiments.test
      paths:
        - path: /

persistence: true

pvc:
  create: true
  storage: 50Gi
  storageClassName: local-zot-vagrant-shared