---
- name: "Install Flannel with kubectl on controller"
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  delegate_to: localhost
  block:
    - name: Apply Flannel with Kustomize
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig.dest }}"
        definition: "{{ lookup('kubernetes.core.kustomize', dir='flannel') }}"
