---
- name: "Create .kube directory for project"
  ansible.builtin.file:
    state: directory
    path: "{{ dot_kube_dir }}"
    mode: 0775
  become_user: "{{ lookup('env', 'USER') }}"
  become: true
  delegate_to: localhost
  register: kube_dir
- name: "Fetch admin kubeconfig form control node"
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ kube_dir.path }}/kubeconfig-admin"
    flat: true
  register: kubeconfig
