---
- name: "Initialize control plane node"
  ansible.builtin.command:
  args:
    cmd: "kubeadm init --node-name {{ ansible_hostname }} --pod-network-cidr=10.244.0.0/16"
    creates: /etc/kubernetes/manifests/*
  register: kube_init
- name: "Grab kubeconfig"
  ansible.builtin.import_tasks:
    file: "kubeconfig.yml"
- name: "Install Flannel CNI"
  ansible.builtin.import_tasks:
    file: "flannel.yml"
