---
# taken from https://github.com/freehck/ansible-role-disable-swap/blob/master/tasks/main.yml
# and https://github.com/geerlingguy/ansible-role-swap/blob/master/tasks/disable.yml
- name: Disable swap immediately
  ansible.builtin.command: swapoff -a
  changed_when: true
  when: ansible_swaptotal_mb > 0

- name: Remove swap from fstab
  ansible.builtin.lineinfile:
    path: '/etc/fstab'
    regexp: '\sswap\s'
    state: 'absent'

- name: "Update and Upgrade Apt Packages"
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Add Required APT repositories
  ansible.builtin.include_tasks:
    file: "k8s-apt-repositories.yml"

- name: Install Kubeadm, CRI-O and related packages
  ansible.builtin.apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
      - cri-o
      - crun
    allow_downgrade: true

- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: "hold"
  loop:
    - kubeadm
    - kubelet
    - kubectl
