---
- name: "Copy externally generate public SSH key"
  ansible.posix.authorized_key:
    user: vagrant
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/vagrant-k8s-experiments.pub') }}"
    exclusive: true
- name: "Update and Upgrade Apt Packages"
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Setup Kubernetes APT repository
  block:
    - name: "Obtain Kubernetes apt gpg key"
      ansible.builtin.get_url:
        url: "https://pkgs.k8s.io/core:/stable:/v{{ kube_major_version }}/deb/Release.key"
        dest: "/usr/share/keyrings/kubernetes-archive-keyring.gpg"
        mode: "0644"
    - name: "Add Kubernetes repository to APT"
      ansible.builtin.apt_repository:
        # Why no focal?
        repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kube_major_version }}/deb/ /"
        filename: kubernetes

- name: Setup CRI-O APT repositories
  ansible.builtin.include_tasks:
    file: "cri-o.yml"
- name: Install Kubeadm, CRI-O and related packages
  ansible.builtin.apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
      - cri-o
      - cri-o-runc
      - cri-tools
      - criu
      - libyajl2
    allow_downgrade: true

- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: "hold"
  loop:
    - kubeadm
    - kubelet
    - kubectl

- name: Disable Swap
  ansible.builtin.include_tasks:
    file: "disable-swap.yml"
- name: Enable Kernel Parameters
  ansible.builtin.include_tasks:
    file: "sysctl.yml"

- name: Enable and Start CRI-O service
  ansible.builtin.systemd:
    unit: crio
    enabled: true
    state: started

- name: Enable and Start kubelet service
  ansible.builtin.systemd:
    unit: kubelet
    enabled: true
    state: started
