---
- name: "Copy externally generate public SSH key"
  ansible.posix.authorized_key:
    user: vagrant
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/vagrant-k8s-experiments.pub') }}"
    exclusive: true

- name: Install and Update Packages
  ansible.builtin.include_tasks:
    file: "{{ ansible_os_family | lower }}.yml"

- name: Install Flannel required binaries
  ansible.builtin.import_tasks:
    file: install-cni-plugin.yml

- name: Enable Kernel Parameters
  ansible.builtin.import_tasks:
    file: "sysctl.yml"

- name: Configure CRI-O
  ansible.builtin.copy:
    src: crio-crun-runtime.conf
    dest: /etc/crio/crio.conf
    mode: "0600"

- name: Enable and Start CRI-O service
  ansible.builtin.systemd:
    unit: crio
    enabled: true
    state: started

- name: Enable and Start kubelet service
  ansible.builtin.systemd:
    unit: kubelet
    enabled: true
    state: started
