---
- name: Configure private interface eth1 with static ip
  block:
    - name: Delete any previous configured private interface
      community.general.nmcli:
        conn_name: Wired connection 2
        state: absent
        conn_reload: true
    - name: Create new eth1 interface
      community.general.nmcli:
        conn_name: Private Vagrant Interface
        ifname: eth1
        ip4: "{{ private_ip }}/24"
        method4: manual
        type: ethernet
        state: present
        conn_reload: true

- name: Update Packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true

# mechanism is different as Fedora uses ZRAM/creates a RAM drive...
- name: Disable swap unit immediately
  ansible.builtin.systemd:
    unit: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - systemd-zram-setup@zram0
    - dev-zram0.swap
  ignore_errors: true

- name: Remove ZRAM generator defaults
  ansible.builtin.dnf:
    name:
      - zram-generator
      - zram-generator-defaults
    state: absent

- name: Add Kubernetes Repository
  ansible.builtin.yum_repository:
    name: Kubernetes
    description: Kubernetes repository from pkg.k8s.io
    baseurl:
      - https://pkgs.k8s.io/core:/stable:/v{{ kube_major_version }}/rpm/
    enabled: true
    gpgcheck: true
    gpgkey:
      - https://pkgs.k8s.io/core:/stable:/v{{ kube_major_version }}/rpm/repodata/repomd.xml.key

- name: Add CRI-O Repository
  ansible.builtin.yum_repository:
    name: CRI-O
    description: CRI-O repository from pkg.k8s.io
    baseurl:
      - https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{ cri_o_major_version }}/rpm/
    enabled: true
    gpgcheck: true
    gpgkey:
      - https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{ cri_o_major_version }}/rpm/repodata/repomd.xml.key

- name: Install Kubeadm, CRI-O and related packages
  ansible.builtin.dnf:
    name:
      - kubeadm
      - kubelet
      - kubectl
      - cri-o
      - crun-wasm
    allow_downgrade: true
    state: present
