controller:
  containerPort:
    http: 8080
    https: 8443
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
  service:
    enabled: false
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
