controller:
  containerPort:
    http: 80
    https: 443
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
  service:
    enabled: false
  # nodeSelector:
  #   node-role.kubernetes.io/control-plane: ""
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
