apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-zot-vagrant-shared
provisioner: kubernetes.io/no-provisioner # indicates that this StorageClass does not support automatic provisioning
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zot-storage-1
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-zot-vagrant-shared
  local:
    path: /vagrant/zot-storage-volumes/zot-storage-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vagrant-k8s-worker-1
                - vagrant-k8s-worker-2
