apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/flannel-io/flannel/v0.26.1/Documentation/kube-flannel.yml

patches: 
  - target: 
      group: apps
      version: v1
      kind: DaemonSet
      name: kube-flannel-ds
    path: flannel-args-patch.yaml
